--- 
- name: Synchronize profile across hosts
  synchronize:
    src="{{ local_home }}/.dotfiles"
    dest="{{ remote_home }}"
    archive=yes
    checksum=yes
    compress=no
    mode=push
    perms=yes
    recursive=yes
    rsync_timeout=10
    rsync_opts="{{ rsync_options }}"
  notify:
    - install

- name: Copy/create files
  copy:
    src="{{ local_home }}/.etc/sudo"
    dest="{{remote_home}}/.etc/sudo"
    owner="{{ username }}"
    group="{{ groupname }}"
    mode=0600

- name: update security service config
  template:
    src=SecurityService/config/ServiceConfig.xml
    dest="{{remote_home}}/.etc/SecurityService/config/ServiceConfig.xml"

- name: update esol-core service config
  template:
    src=eSolutionsCore/config/ServiceConfig.xml
    dest="{{remote_home}}/.etc/eSolutionsCore/config/ServiceConfig.xml"

- name: update esol-core mail config
  template:
    src=eSolutionsCore/mail/MailConfig.properties
    dest="{{remote_home}}/.etc/eSolutionsCore/mail/MailConfig.properties"
